Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android', 'iOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'FreeBSD' ]
  cmake-options: -DBUILD_EXAMPLES=ON
  cppcheck-ignore-files: ['templates/']
