/*
 *  SPDX-FileCopyrightText: 2026 Marco Martin <mart@kde.org>
 *
 *  SPDX-License-Identifier: LGPL-2.0-or-later
 */

#include "kirigamicontrolsplugin.h"
#include "styleselector.h"

#include <QFile>
#include <QQmlComponent>
#include <QQuickStyle>

using namespace Qt::StringLiterals;

// This is required for declarative registration to work on Windows.
// This is normally generated by Qt but since we need a manually written plugin
// file, we need to include this ourselves.
extern void qml_register_types_org_kde_kirigami_controls();
Q_GHS_KEEP_REFERENCE(qml_register_types_org_kde_kirigami_controls)

KirigamiControlsPlugin::KirigamiControlsPlugin(QObject *parent)
    : QQmlExtensionPlugin(parent)
{
    // See above.
    volatile auto registration = &qml_register_types_org_kde_kirigami_controls;
    Q_UNUSED(registration)
}

void KirigamiControlsPlugin::registerTypes(const char *uri)
{
    Q_ASSERT(QLatin1String(uri) == "org.kde.kirigami.controls"_L1);

    qmlRegisterModuleImport(uri, QQmlModuleImportModuleAny, "org.kde.kirigami.controls.Basic", QQmlModuleImportLatest, QQmlModuleImportAuto);

    // FIXME: Kirigami::Platform::StyleSelector::style() doesn't seem to work
    QString style = QQuickStyle::name(); // Kirigami::Platform::StyleSelector::style();
    QQmlEngine engine;
    bool found = false;
    QString pathStyle(style);
    pathStyle.replace('.'_L1, u"/"_s);
    for (const auto &path : engine.importPathList()) {
        if (QFile::exists(path % u"/org/kde/kirigami/controls/"_s % pathStyle)) {
            found = true;
            break;
        }
    }
    if (found && style != u"Basic"_s) {
        qmlRegisterModuleImport(uri,
                                QQmlModuleImportModuleAny,
                                (u"org.kde.kirigami.controls."_s % style).toUtf8().constData(),
                                QQmlModuleImportLatest,
                                QQmlModuleImportAuto);
    }
}

#include "moc_kirigamicontrolsplugin.cpp"
